version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
      - run: npm run lint
